In [1]:
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
import os
print("Orig Dir:",os.getcwd())
os.chdir('../../')
print("Current Dir:",os.getcwd())

Orig Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering\models\playground
Current Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering


# With DataFrameInterpolator

In [3]:
data_path = 'data/gesture/features/features_flip_c_03_120.csv'
df_orig = pd.read_csv(data_path,sep=',')

In [4]:
df_orig.head(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0   341.136444   224.253407  320.787999  274.947119      329.514176   
1   340.985901   224.344366  320.455079  275.406629      329.389916   
2   339.929797   222.910622  320.485332  274.863216      328.574083   

   leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
0      166.895228   345.275067   277.081232                    0   
1      166.027360   345.465304   277.669048                  121   
2      164.447614   345.679107   277.607702                  124   

   ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
0             0.0    256.999411    225.093688  281.429514  272.660262   
1           121.0    256.989746    225.065718  281.315210  273.121688   
2           245.0    257.143566    224.858589  281.088004  273.002894   

   rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
0       262.775556       169.641120    253.241117    271.500238  
1       262.903829       169.255270    252.963656    271.032473  
2       263.136312       168.805475    253.317534    272.038940

In [5]:
df_orig.tail(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
512   319.319667   230.708748  298.824522  282.950745      307.895506   
513   319.925200   231.459856  301.842279  284.897455      307.853791   
514   320.256985   231.464999  303.479078  282.911811      308.280313   

     leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
512      172.928437   324.299526   284.834090                  123   
513      173.172676   327.859531   288.420817                  127   
514      173.255101   327.940133   288.014988                  125   

     ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
512         63377.0    239.445354    228.770849  256.039323  280.984864   
513         63504.0    238.713065    228.260810  259.120375  288.724712   
514         63629.0    238.492736    229.590148  255.973041  281.096239   

     rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
512       241.841628       173.552154    224.964407    281.640640  
513       241.122537       174.043648    225.099266    282.891109  
514       240.860414       176.263707    224.645867    282.764413

In [6]:
from app_local.module import DataFrameInterpolator

In [7]:
di = DataFrameInterpolator()
di.display_information()

In [8]:
new_df = di.scaleDataFrame(df_orig, actual_length_in_ms=64048, time_of_first_frame='avg')
new_df.head(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0   341.136444   224.253407  320.787999  274.947119      329.514176   
1   340.985901   224.344366  320.455079  275.406629      329.389916   
2   339.929797   222.910622  320.485332  274.863216      328.574083   

   leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
0      166.895228   345.275067   277.081232                  0.0   
1      166.027360   345.465304   277.669048                121.0   
2      164.447614   345.679107   277.607702                125.0   

   ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
0           124.0    256.999411    225.093688  281.429514  272.660262   
1           245.0    256.989746    225.065718  281.315210  273.121688   
2           370.0    257.143566    224.858589  281.088004  273.002894   

   rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
0       262.775556       169.641120    253.241117    271.500238  
1       262.903829       169.255270    252.963656    271.032473  
2       263.136312       168.805475    253.317534    272.038940

In [9]:
new_df.tail(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
512   319.319667   230.708748  298.824522  282.950745      307.895506   
513   319.925200   231.459856  301.842279  284.897455      307.853791   
514   320.256985   231.464999  303.479078  282.911811      308.280313   

     leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
512      172.928437   324.299526   284.834090                124.0   
513      173.172676   327.859531   288.420817                127.0   
514      173.255101   327.940133   288.014988                126.0   

     ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
512         63795.0    239.445354    228.770849  256.039323  280.984864   
513         63922.0    238.713065    228.260810  259.120375  288.724712   
514         64048.0    238.492736    229.590148  255.973041  281.096239   

     rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
512       241.841628       173.552154    224.964407    281.640640  
513       241.122537       174.043648    225.099266    282.891109  
514       240.860414       176.263707    224.645867    282.764413

In [10]:
new_df = di.get_new_df(new_df, 50)
di.display_information()

FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 515
	 [124. 245. 370. 493. 613.] ... [63542. 63671. 63795. 63922. 64048.] 

New Time:
	Number of Frames: 1280
	 [124 174 224 274 324] ... [63874 63924 63974 64024 64074] 

Original DataFrame Shape: (515, 18)
New DataFrame Shape: (1280, 17)


# With DataEnsembler

In [11]:
from app_local.module import DataEnsembler
de = DataEnsembler()
print(DataEnsembler.video_stats_pattern)


# after investigating the datafiles, our DataEnsembler instance will have a vs_stats dataframe
de.investigate_available_datafiles(data_dir='data/gesture/')
de.video_stats

(?P<movement>[a-z]*)_(?P<person>[a-z]*)_(?P<filenum>\d*)


file  actual_length  from_extraction  delta
0      flip_c_01          68677            66290   2387
1      flip_c_02          63117            60562   2555
2      flip_c_03          64048            63629    419
3      flip_l_01          70576            69924    652
4      flip_l_02          62915            62303    612
5      flip_l_03          64248            63629    619
6      flip_p_01          66712            66095    617
7      land_c_01          63482            62870    612
8      land_c_02          64547            63666    881
9      land_c_03          64114            63556    558
10     land_l_01          68994            68204    790
11     land_l_02          61750            60163   1587
12     land_l_03          64814            63915    899
13     left_c_01          62482            61139   1343
14     left_c_02          61017            60053    964
15     left_c_03          62982            61599   1383
16     left_l_01          65180            61670   3510
17     left_l_02          61750            61086    664
18     left_l_03          63515            62922    593
19     move_c_01          70709            69928    781
20     move_l_01          73274            72651    623
21     move_p_01          70244            69061   1183
22     none_p_01          53356            54506  -1150
23    right_c_01          69011            60680   8331
24    right_c_02         105258           104692    566
25    right_l_01          69410            63608   5802
26    right_l_02          65980            65414    566
27    right_l_03          61317            60407    910
28  takeoff_l_01          65647            64669    978
29  takeoff_c_01          63448            62639    809
30  takeoff_c_02          61217            60658    559
31  takeoff_c_03          78103            77498    605
32  takeoff_l_02          68444            67195   1249
33  takeoff_l_03          62383            61528    855

In [12]:
de.combined_data_files_df.head()

filename_features       filename_labels
0  features_flip_c_01_120.csv  labels_flip_c_01.csv
1  features_flip_c_02_120.csv  labels_flip_c_02.csv
2  features_flip_c_03_120.csv  labels_flip_c_03.csv
3  features_flip_l_01_120.csv  labels_flip_l_01.csv
4  features_flip_l_02_120.csv  labels_flip_l_02.csv

In [13]:
de.load_data()

In [14]:
de.rescale_data_frames(time_of_first_frame='avg',verbose=False)

In [15]:
de.interpolate_data_frames(frmlen = 50, verbose=True)

0: (620, 18) (1373, 17)
1: (536, 18) (1261, 17)
2: (515, 18) (1280, 17)
3: (667, 18) (1411, 17)
4: (525, 18) (1257, 17)
5: (483, 18) (1284, 17)
6: (618, 18) (1334, 17)
7: (457, 18) (1268, 17)
8: (507, 18) (1290, 17)
9: (493, 18) (1281, 17)
10: (509, 18) (1379, 17)
11: (453, 18) (1234, 17)
12: (483, 18) (1295, 17)
13: (568, 18) (1249, 17)
14: (567, 18) (1220, 17)
15: (566, 18) (1259, 17)
16: (558, 18) (1303, 17)
17: (552, 18) (1234, 17)
18: (566, 18) (1270, 17)
19: (633, 18) (1413, 17)
20: (638, 18) (1465, 17)
21: (607, 18) (1404, 17)
22: (477, 18) (1066, 17)
23: (531, 18) (1379, 17)
24: (940, 18) (2104, 17)
25: (562, 18) (1387, 17)
26: (564, 18) (1319, 17)
27: (522, 18) (1225, 17)
28: (486, 18) (1268, 17)
29: (541, 18) (1224, 17)
30: (586, 18) (1561, 17)
31: (505, 18) (1312, 17)
32: (498, 18) (1368, 17)
33: (433, 18) (1246, 17)


In [16]:
for i,interp in enumerate(de.Interpolators):
    print("")
    print(str(i))
    interp.display_information()


0
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 620
	 [110. 220. 345. 465. 580.] ... [68182. 68321. 68450. 68568. 68677.] 

New Time:
	Number of Frames: 1373
	 [110 160 210 260 310] ... [68510 68560 68610 68660 68710] 

Original DataFrame Shape: (620, 18)
New DataFrame Shape: (1373, 17)

1
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 536
	 [117. 221. 330. 438. 544.] ... [62656. 62763. 62875. 62983. 63117.] 

New Time:
	Number of Frames: 1261
	 [117 167 217 267 317] ... [62917 62967 63017 63067 63117] 

Original DataFrame Shape: (536, 18)
New DataFrame Shape: (1261, 17)

2
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 515
	 [124. 245. 370. 493. 613.] ... [63542. 63671. 63795. 63922. 64048.] 

New Time:
	Number of Frames: 1280
	 [124 174 224 274 324] ... [63874 63924 63974 64024 64074] 

Original DataFrame Shape: (515, 18)
New DataFrame Shape: (1280, 17)

3
FrameLength in Milliseconds: 50 

Original Time:
	Number of Fram

In [17]:
de.assemble_data(max_error=500,tolerance_range=400)

In [18]:
de.display_information()

i: 0 	shape X: (1356, 18, 16) 	shape y: (1356,) 	count: 65
i: 1 	shape X: (1244, 18, 16) 	shape y: (1244,) 	count: 113
i: 2 	shape X: (1263, 18, 16) 	shape y: (1263,) 	count: 120
i: 3 	shape X: (1394, 18, 16) 	shape y: (1394,) 	count: 176
i: 4 	shape X: (1240, 18, 16) 	shape y: (1240,) 	count: 104
i: 5 	shape X: (1267, 18, 16) 	shape y: (1267,) 	count: 121
i: 6 	shape X: (1317, 18, 16) 	shape y: (1317,) 	count: 104
i: 7 	shape X: (1251, 18, 16) 	shape y: (1251,) 	count: 49
i: 8 	shape X: (1273, 18, 16) 	shape y: (1273,) 	count: 88
i: 9 	shape X: (1264, 18, 16) 	shape y: (1264,) 	count: 96
i: 10 	shape X: (1362, 18, 16) 	shape y: (1362,) 	count: 80
i: 11 	shape X: (1217, 18, 16) 	shape y: (1217,) 	count: 64
i: 12 	shape X: (1278, 18, 16) 	shape y: (1278,) 	count: 88
i: 13 	shape X: (1232, 18, 16) 	shape y: (1232,) 	count: 0
i: 14 	shape X: (1203, 18, 16) 	shape y: (1203,) 	count: 0
i: 15 	shape X: (1242, 18, 16) 	shape y: (1242,) 	count: 0
i: 16 	shape X: (1286, 18, 16) 	shape y: (1286,

In [19]:
de.data[0].head(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0   330.652879   198.063794  317.111272  247.594685      318.645721   
1   330.516778   194.654546  317.109291  247.814561      319.154056   
2   330.613449   193.583187  317.252554  247.837887      319.543420   

   leftShoulder_y  leftWrist_x  leftWrist_y  rightElbow_x  rightElbow_y  \
0      141.643284   338.098494   250.403484    244.917285    202.445251   
1      141.927192   339.203544   250.203695    246.078051    201.711251   
2      141.695772   339.832609   250.075551    246.168333    201.316533   

   rightHip_x  rightHip_y  rightShoulder_x  rightShoulder_y  rightWrist_x  \
0  275.317313  247.668226       252.832705       138.901809    247.234862   
1  276.744393  248.291192       253.094001       138.310876    247.648228   
2  276.585796  248.176499       253.702561       137.773488    248.037164   

   rightWrist_y  ms_since_start  
0    250.259751             110  
1    252.383868             160  
2    252.992357             210

In [20]:
de.data[0].tail(3)

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
1370   292.632753   232.596761  280.791249  283.532374      285.724549   
1371   290.209534   232.223023  279.866342  285.272385      285.163460   
1372   289.412547   232.244984  280.232776  286.453424      285.136993   

      leftShoulder_y  leftWrist_x  leftWrist_y  rightElbow_x  rightElbow_y  \
1370      179.007104   296.005683   260.172785    203.668775    227.821580   
1371      177.939146   283.073000   256.548099    204.097775    227.897521   
1372      177.276252   277.792111   256.843287    204.921382    228.074652   

      rightHip_x  rightHip_y  rightShoulder_x  rightShoulder_y  rightWrist_x  \
1370  242.262471  284.657207       218.121446       176.606893    222.639620   
1371  241.148246  285.026493       217.487580       177.274672    221.585087   
1372  240.392729  285.062249       217.358494       177.692711    220.701188   

      rightWrist_y  ms_since_start  
1370    252.666433           68610  
1371    251.754410           68660  
1372    253.244256           68710