In [1]:
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
!conda list scipy

# packages in environment at C:\ProgramData\Anaconda3\envs\DataScienceRetreat:
#
# Name                    Version                   Build  Channel
scipy                     1.1.0            py36h4f6bf74_1  


In [3]:
import os
print("Orig Dir:",os.getcwd())
os.chdir('../../')
print("Current Dir:",os.getcwd())

Orig Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering\models\playground
Current Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering


In [4]:
data_path = 'data/gesture/features/features_flip_c_03_120.csv'
df_orig = pd.read_csv(data_path,sep=',')

In [5]:
df_orig.head()

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0   341.136444   224.253407  320.787999  274.947119      329.514176   
1   340.985901   224.344366  320.455079  275.406629      329.389916   
2   339.929797   222.910622  320.485332  274.863216      328.574083   
3   341.394664   225.080272  323.362793  277.252602      327.161964   
4   341.007135   227.292845  320.850446  280.183320      326.259811   

   leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
0      166.895228   345.275067   277.081232                    0   
1      166.027360   345.465304   277.669048                  121   
2      164.447614   345.679107   277.607702                  124   
3      165.040823   345.486792   282.963012                  123   
4      167.356121   342.353060   285.637142                  119   

   ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
0             0.0    256.999411    225.093688  281.429514  272.660262   
1           121.0    256.989746    225.065718  281.315210  273.121688   
2           245.0    257.143566    224.858589  281.088004  273.002894   
3           368.0    256.015686    224.441979  280.673399  273.297257   
4           487.0    255.963889    224.110870  280.559333  274.064114   

   rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
0       262.775556       169.641120    253.241117    271.500238  
1       262.903829       169.255270    252.963656    271.032473  
2       263.136312       168.805475    253.317534    272.038940  
3       262.428639       167.931032    251.685311    271.837686  
4       261.804933       166.962579    253.027392    270.509372

In [6]:
from app_local.module import DataFrameInterpolator

In [7]:
di = DataFrameInterpolator()
di.display_information()

In [8]:
new_df = di.scaleDataFrame(df_orig, 64048, 'avg')
new_df = di.get_new_df(new_df, 50)
di.display_information()

FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 515
	 [124. 245. 370. 493. 613.] ... [63542. 63671. 63795. 63922. 64048.] 

New Time:
	Number of Frames: 1280
	 [124 174 224 274 324] ... [63874 63924 63974 64024 64074] 

Original DataFrame Shape: (515, 18)
New DataFrame Shape: (1280, 17)


In [9]:
from app_local.module import DataEnsembler
de = DataEnsembler()

de.investigate_available_datafiles(data_dir='data/gesture/')
de.load_data()
de.rescale_data_frames()
de.interpolate_data_frames(50)

In [10]:
for i,interp in enumerate(de.Interpolators):
    print("")
    print(str(i))
    interp.display_information()


0
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 620
	 [  0. 107. 228. 344. 455.] ... [65811. 65946. 66071. 66185. 66290.] 

New Time:
	Number of Frames: 1327
	 [  0  50 100 150 200] ... [66100 66150 66200 66250 66300] 

Original DataFrame Shape: (620, 18)
New DataFrame Shape: (1327, 17)

1
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 536
	 [117. 221. 330. 438. 544.] ... [62656. 62763. 62875. 62983. 63117.] 

New Time:
	Number of Frames: 1261
	 [117 167 217 267 317] ... [62917 62967 63017 63067 63117] 

Original DataFrame Shape: (536, 18)
New DataFrame Shape: (1261, 17)

2
FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 515
	 [124. 245. 370. 493. 613.] ... [63542. 63671. 63795. 63922. 64048.] 

New Time:
	Number of Frames: 1280
	 [124 174 224 274 324] ... [63874 63924 63974 64024 64074] 

Original DataFrame Shape: (515, 18)
New DataFrame Shape: (1280, 17)

3
FrameLength in Milliseconds: 50 

Original Time:
	Number of Fram

In [11]:
de.assemble_data(max_error=500,tolerance_range=400,framelength_strategy=50)

In [12]:
de.display_information()

i: 0 	shape X: (1287, 41, 16) 	shape y: (1287,) 	count: 61
i: 1 	shape X: (1221, 41, 16) 	shape y: (1221,) 	count: 113
i: 2 	shape X: (1240, 41, 16) 	shape y: (1240,) 	count: 120
i: 3 	shape X: (1360, 41, 16) 	shape y: (1360,) 	count: 191
i: 4 	shape X: (1217, 41, 16) 	shape y: (1217,) 	count: 104
i: 5 	shape X: (1244, 41, 16) 	shape y: (1244,) 	count: 121
i: 6 	shape X: (1294, 41, 16) 	shape y: (1294,) 	count: 104
i: 7 	shape X: (1219, 41, 16) 	shape y: (1219,) 	count: 48
i: 8 	shape X: (1250, 41, 16) 	shape y: (1250,) 	count: 88
i: 9 	shape X: (1241, 41, 16) 	shape y: (1241,) 	count: 96
i: 10 	shape X: (1326, 41, 16) 	shape y: (1326,) 	count: 85
i: 11 	shape X: (1194, 41, 16) 	shape y: (1194,) 	count: 64
i: 12 	shape X: (1255, 41, 16) 	shape y: (1255,) 	count: 88
i: 13 	shape X: (1184, 41, 16) 	shape y: (1184,) 	count: 0
i: 14 	shape X: (1163, 41, 16) 	shape y: (1163,) 	count: 0
i: 15 	shape X: (1193, 41, 16) 	shape y: (1193,) 	count: 0
i: 16 	shape X: (1195, 41, 16) 	shape y: (1195,