In [1]:
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
!conda list scipy

# packages in environment at C:\ProgramData\Anaconda3\envs\DataScienceRetreat:
#
# Name                    Version                   Build  Channel
scipy                     1.1.0            py36h4f6bf74_1  


In [3]:
import os
print("Orig Dir:",os.getcwd())
os.chdir('../../')
print("Current Dir:",os.getcwd())

Orig Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering\models\playground
Current Dir: C:\Users\p.schambach\Desktop\DSR\drone_steering


In [4]:
data_path = 'data/gesture/features/features_flip_c_03_120.csv'
df_orig = pd.read_csv(data_path,sep=',')

In [5]:
df_orig.head()

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0   341.136444   224.253407  320.787999  274.947119      329.514176   
1   340.985901   224.344366  320.455079  275.406629      329.389916   
2   339.929797   222.910622  320.485332  274.863216      328.574083   
3   341.394664   225.080272  323.362793  277.252602      327.161964   
4   341.007135   227.292845  320.850446  280.183320      326.259811   

   leftShoulder_y  leftWrist_x  leftWrist_y  ms_since_last_frame  \
0      166.895228   345.275067   277.081232                    0   
1      166.027360   345.465304   277.669048                  121   
2      164.447614   345.679107   277.607702                  124   
3      165.040823   345.486792   282.963012                  123   
4      167.356121   342.353060   285.637142                  119   

   ms_since_start  rightElbow_x  rightElbow_y  rightHip_x  rightHip_y  \
0             0.0    256.999411    225.093688  281.429514  272.660262   
1           121.0    256.989746    225.065718  281.315210  273.121688   
2           245.0    257.143566    224.858589  281.088004  273.002894   
3           368.0    256.015686    224.441979  280.673399  273.297257   
4           487.0    255.963889    224.110870  280.559333  274.064114   

   rightShoulder_x  rightShoulder_y  rightWrist_x  rightWrist_y  
0       262.775556       169.641120    253.241117    271.500238  
1       262.903829       169.255270    252.963656    271.032473  
2       263.136312       168.805475    253.317534    272.038940  
3       262.428639       167.931032    251.685311    271.837686  
4       261.804933       166.962579    253.027392    270.509372

In [6]:
from app_local.module import DataFrameInterpolator

In [7]:
di = DataFrameInterpolator()
di.display_information()

In [8]:
new_df = di.scaleDataFrame(df_orig, 64048, 'avg')
new_df = di.get_new_df(new_df, 50)
di.display_information()

FrameLength in Milliseconds: 50 

Original Time:
	Number of Frames: 515
	 [124. 245. 370. 493. 613.] ... [63542. 63671. 63795. 63922. 64048.] 

New Time:
	Number of Frames: 1280
	 [124 174 224 274 324] ... [63874 63924 63974 64024 64074] 

Original DataFrame Shape: (515, 18)
New DataFrame Shape: (1280, 17)


In [16]:
from app_local.module import DataEnsembler
de = DataEnsembler()

de.investigate_available_datafiles(data_dir='data/gesture/')
de.load_data()
de.rescale_data_frames()
de.actual_lengths_df

filename_features actual_length
1      features_flip_c_02_120.csv         63117
2      features_flip_c_03_120.csv         64048
4      features_flip_l_02_120.csv         62915
5      features_flip_l_03_120.csv         64248
6      features_flip_p_01_120.csv         66712
8      features_land_c_02_120.csv         64547
9      features_land_c_03_120.csv         64114
11     features_land_l_02_120.csv         61750
12     features_land_l_03_120.csv         64814
29  features_takeoff_c_02_120.csv         61217
30  features_takeoff_c_03_120.csv         78103
32  features_takeoff_l_02_120.csv         68444
33  features_takeoff_l_03_120.csv         62383

In [10]:
df1 = de.data[1]
df1

leftElbow_x  leftElbow_y   leftHip_x   leftHip_y  leftShoulder_x  \
0     343.619375   226.269678  323.926912  272.584208      329.932556   
1     340.593654   221.387116  321.866580  273.539411      328.487448   
2     339.182796   220.708194  320.048781  276.074290      327.524268   
3     340.329506   218.872136  322.482532  275.353883      323.780115   
4     339.064258   217.144752  322.590305  275.638462      323.259628   
5     338.808484   218.492473  322.403433  274.515260      322.042966   
6     338.202107   217.083628  322.437446  268.915659      321.479597   
7     337.449281   216.114390  322.451141  270.733295      323.194727   
8     339.223645   218.214009  320.258982  271.677060      323.987090   
9     340.265475   214.511602  320.496619  268.061352      320.474236   
10    339.667034   200.349346  318.775836  261.667674      321.500856   
11    339.239848   193.297741  318.177838  259.963732      320.020389   
12    342.840069   175.394200  326.282069  254.405553      322.475606   
13    341.732672   174.731577  329.182369  252.737519      322.985390   
14    345.134334   179.930681  328.759390  254.896202      325.868217   
15    344.900244   197.839781  327.881641  254.899875      328.968175   
16    349.314134   199.492632  327.711486  255.953220      329.601799   
17    350.939235   206.829993  329.375977  254.411443      331.751180   
18    351.516131   207.728497  325.896457  257.290349      332.567606   
19    350.758299   200.801683  329.933300  257.991162      333.357695   
20    352.713896   205.334137  329.136274  254.525436      331.565669   
21    350.669623   204.469211  330.957491  251.725296      330.805573   
22    352.651213   195.613346  331.093166  254.793430      333.743976   
23    354.390410   198.277460  330.175419  250.849961      332.090869   
24    350.649986   196.259801  331.332592  249.256374      330.758514   
25    342.328628   197.969909  330.547854  250.591027      331.009632   
26    369.141814   216.092424  350.270325  266.212339      356.271281   
27    366.503215   210.638872  347.121814  266.369019      352.112777   
28    363.052736   209.187373  346.171507  265.101150      349.479073   
29    363.277615   215.192308  343.840952  266.861108      346.557455   
..           ...          ...         ...         ...             ...   
506   332.318212   224.995794  307.759987  280.454788      312.757572   
507   329.410818   226.889380  306.596864  283.987840      310.559763   
508   320.190134   229.996460  298.979725  283.608020      308.570743   
509   312.241913   236.658037  299.575683  278.966355      307.183426   
510   297.481026   233.342285  300.963606  268.175840      302.351330   
511   279.840404   221.830578  296.772936  275.203747      298.948112   
512   270.612990   211.945193  294.894203  271.289097      298.328390   
513   281.878228   191.739909  296.929563  271.027403      300.999751   
514   288.445964   179.075804  297.683882  270.240132      300.197590   
515   286.043061   116.746519  297.826205  270.618927      295.278445   
516   305.632043   136.393126  290.697498  269.993550      298.107054   
517   308.859645   111.394154  300.959048  273.000026      300.296388   
518   322.582151    95.819346  302.503627  271.087082      304.135689   
519   330.632478    99.581489  305.018090  269.174776      304.858414   
520   332.020946   112.092467  307.399558  268.725804      306.058404   
521   342.338507   119.444959  308.265115  270.924448      309.091725   
522   362.662668   124.656097  306.564722  274.549653      308.221332   
523   363.561906   141.125122  307.914957  288.018380      307.591279   
524   372.104060   158.502154  308.907271  275.845981      313.330318   
525   366.865238   183.606821  311.863424  276.648682      311.621580   
526   363.366048   197.830126  312.155815  277.936387      310.331962   
527   348.157975   216.627815  313.019828  279.677273      313.306394   
528   332.665104   230.904544  308.981346  282.586351      315.

In [11]:
from app_local.module import LabelGenerator

In [12]:
data_path = 'data/gesture/features/features_flip_p_01_120.csv'
labels_path = 'data/gesture/labels_timebased/labels_flip_p_01.csv'
data = pd.read_csv(data_path, sep = ',')
raw_labels = pd.read_csv(labels_path, sep = ',')
print("Data Shape:", data.shape)

di = DataFrameInterpolator()
data = di.scaleDataFrame(df=data, actual_length_in_ms=66712, time_of_first_frame='avg')
data.head()
di.display_information()

lgen = LabelGenerator(data=data, raw_labels=raw_labels, ms_per_frame=120)
lgen.fit_range(50,500)
lgen.set_labels()
lgen.labeled_data.head()

lgen.extract_training_data()


Data Shape: (618, 18)


In [13]:
lgen.labeled_data[["ms_since_start","label"]].head(20)

ms_since_start  label
0              107      0
1              214      0
2              324      0
3              434      0
4              534      0
5              635      0
6              732      0
7              836      0
8              938      0
9             1037      0
10            1139      0
11            1238      0
12            1336      0
13            1438      0
14            1540      0
15            1643      0
16            1744      0
17            1847      0
18            1947      0
19            2050      0

In [14]:
lgen.sequence_end_time[lgen.y> 0]

array([20253, 20368, 24591, 28520, 36124, 36230, 36343, 40508, 44447,
       48364, 52394, 56301, 56415, 60206, 60312, 64533])

In [15]:
2000

2000